# Generated by Django 3.2.25 on 2025-05-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='name',
            new_name='item_name',
        ),
    ]
