# Generated by Django 4.2 on 2025-07-10 05:47

from django.db import migrations, models
import inventory.utils


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='cpu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='gpu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('In Repair', 'In Repair'), ('Decommissioned', 'Decommissioned'), ('In Transit', 'In Transit')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='uid_no',
            field=models.CharField(default=inventory.utils.generate_uid_no, max_length=100, unique=True),
        ),
    ]
