# Generated by Django 3.2.25 on 2025-05-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_name_inventoryitem_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='in_transit',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
