# Generated by Django 4.2 on 2025-07-10 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_created_at_inventoryitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorylog',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='installed_software',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='os',
        ),
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('In Repair', 'In Repair'), ('Disposed', 'Disposed'), ('In Transit', 'In Transit')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='uid_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('transferred', 'Transferred'), ('status_change', 'Status Change')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.inventoryitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
