# Generated by Django 4.2 on 2025-07-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorylog_options_remove_inventoryitem_cpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='cpu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='gpu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GPU'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='installed_software',
            field=models.TextField(blank=True, null=True, verbose_name='Installed Software'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operating System'),
        ),
    ]
