# Generated by Django 4.2 on 2025-07-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_cpu_inventoryitem_gpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='uid_no',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
