# Generated by Django 4.2 on 2025-07-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorylog_uid_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='uid_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
