# Generated by Django 4.2 on 2025-07-11 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventorylog_uid_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='uid_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='inventory.inventoryitem'),
        ),
    ]
