# Generated by Django 4.2 on 2025-07-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventoryitem_uid_no_alter_inventorylog_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Laptop', 'LAP'), ('Monitor', 'MON'), ('Printer', 'PRN'), ('Server', 'SRV'), ('Networking Device', 'NET'), ('Desktop PC', 'DESK'), ('Software License', 'SWL'), ('Other', 'OTH')], default='Other', max_length=50),
        ),
        migrations.CreateModel(
            name='UIDCategorySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_prefix', models.CharField(max_length=10)),
                ('year_month', models.CharField(max_length=4)),
                ('last_sequence_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('category_prefix', 'year_month')},
            },
        ),
    ]
