# Generated by Django 4.2 on 2025-07-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryitem_category_uidcategorysequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['-created_at', 'item_name'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterModelOptions(
            name='inventorylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Inventory Log', 'verbose_name_plural': 'Inventory Logs'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='uidcategorysequence',
            options={'verbose_name': 'UID Category Sequence', 'verbose_name_plural': 'UID Category Sequences'},
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='new_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='old_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('transferred', 'Transferred'), ('status_change', 'Status Change'), ('assigned_to_project', 'Assigned to Project'), ('unassigned_from_project', 'Unassigned from Project'), ('location_change', 'Location Change')], max_length=30),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='uid_no',
            field=models.CharField(blank=True, help_text='UID of the item at the time of the log. Preserved even if item is deleted.', max_length=100, null=True),
        ),
    ]
